import { marked } from "marked";
import { useEffect, useRef } from "react";

marked.setOptions({ breaks: true, gfm: true });

function docToMarkdown(doc) {
  if (!doc) return "";
  if (typeof doc === "string") return doc;

  const lines = ["# Solution Document\n"];
  const add = (h, v) => {
    if (!v) return;
    lines.push(`\n## ${h}\n`);
    if (typeof v === "string") {
      lines.push(v + "\n");
    } else if (Array.isArray(v)) {
      v.forEach((item) => {
        if (typeof item === "string") {
          lines.push(`- ${item}\n`);
        } else if (typeof item === "object") {
          Object.entries(item).forEach(([k, val]) =>
            lines.push(`**${k.replace(/_/g, " ")}:** ${val}\n`)
          );
          lines.push("");
        }
      });
    }
  };

  add("Executive Summary", doc.executive_summary);
  add("Recommended Architecture", doc.recommended_architecture);

  if (doc.implementation_plan?.length) {
    lines.push("\n## Implementation Plan\n");
    doc.implementation_plan.forEach((p) => {
      lines.push(`### ${p.phase || "Phase"}\n${p.description || ""}\n`);
      if (p.duration) lines.push(`*Duration: ${p.duration}*\n`);
    });
  }

  add("Key Decisions", doc.key_decisions);
  add("Risks and Mitigations", doc.risks_and_mitigations);
  add("Open Questions", doc.open_questions);

  if (doc.estimated_timeline) {
    lines.push("\n## Estimated Timeline\n" + doc.estimated_timeline + "\n");
  }

  return lines.join("\n");
}

export default function SolutionDocument({ document: doc, sessionId }) {
  const md = docToMarkdown(doc);
  const htmlRef = useRef(null);

  const downloadMd = () => {
    const blob = new Blob([md], { type: "text/markdown" });
    const a = window.document.createElement("a");
    if (!a) return;
    a.href = URL.createObjectURL(blob);
    a.download = `solution-${sessionId?.slice(0, 8) || "doc"}.md`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const downloadPdf = () => {
    // Stub — calls backend which currently returns markdown
    window.location.href = `http://localhost:8000/api/sessions/${sessionId}/export?format=pdf`;
  };

  return (
    <div
      style={{
        maxWidth: 860,
        margin: "32px auto",
        background: "var(--surface)",
        borderRadius: 12,
        border: "1px solid var(--border)",
        boxShadow: "0 4px 24px var(--tint-07)",
        overflow: "hidden",
      }}
    >
      {/* Header */}
      <div
        style={{
          background: "linear-gradient(135deg, var(--sd-navy) 0%, var(--surface-2) 100%)",
          color: "var(--text)",
          padding: "20px 28px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
        }}
      >
        <div>
          <h2 style={{ margin: 0, fontSize: 20, fontWeight: 700 }}>Solution Document</h2>
          <p style={{ margin: "4px 0 0", fontSize: 13, opacity: 0.7 }}>
            Generated by the consulting team
          </p>
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <button
            onClick={downloadMd}
            style={{
              padding: "8px 16px", borderRadius: 7, border: "1px solid var(--sd-white-40)",
              background: "transparent", color: "var(--text)", cursor: "pointer", fontSize: 13,
            }}
          >
            Download Markdown
          </button>
          <button
            onClick={downloadPdf}
            style={{
              padding: "8px 16px", borderRadius: 7, border: "none",
              background: "var(--primary-2)", color: "var(--on-accent)", cursor: "pointer", fontSize: 13,
            }}
          >
            Download PDF
          </button>
        </div>
      </div>

      {/* Content */}
      <div
        ref={htmlRef}
        style={{ padding: "28px 32px", lineHeight: 1.7, color: "var(--text-strong)" }}
        dangerouslySetInnerHTML={{ __html: marked.parse(md) }}
      />

      <style>{`
        .solution-doc h1 { font-size: 1.6rem; }
        .solution-doc h2 { font-size: 1.25rem; border-bottom: 1px solid var(--border); padding-bottom: 6px; margin-top: 24px; }
        .solution-doc h3 { font-size: 1.05rem; color: var(--text); }
        .solution-doc ul { padding-left: 20px; }
        .solution-doc li { margin-bottom: 4px; }
        .solution-doc strong { color: var(--text-max); }
        .solution-doc em { color: var(--muted); }
        .solution-doc p { margin: 8px 0; }
      `}</style>
    </div>
  );
}
